import { useSyncExternalStore } from 'react';
import { nutritionEnglish } from './nutritionEnglish';
export type Language = 'fr' | 'en';
export type WeightUnit = 'kg' | 'lb';
const listeners = new Set<() => void>();
let language: Language = 'fr';
try { if (localStorage.getItem('mygymtracker-language') === 'en') language = 'en'; } catch { /* Storage may be disabled. */ }
export function setLanguage(next: Language) {
  language = next;
  document.documentElement.lang = next;
  try { localStorage.setItem('mygymtracker-language', next); } catch { /* Keep the in-memory preference. */ }
  listeners.forEach(listener => listener());
}
document.documentElement.lang = language;
export function useLanguage() {
  return useSyncExternalStore(listener => { listeners.add(listener); return () => { listeners.delete(listener); }; }, () => language);
}
export function t(text: string): string { return language === 'en' ? (english[text] ?? text) : text; }
export function locale() { return language === 'en' ? 'en-GB' : 'fr-FR'; }
let weightUnit: WeightUnit = 'kg';
const unitListeners = new Set<() => void>();
try { if (localStorage.getItem('mygymtracker-weight-unit') === 'lb') weightUnit = 'lb'; } catch { /* Storage may be disabled. */ }
export function setWeightUnit(next: WeightUnit) { weightUnit = next; try { localStorage.setItem('mygymtracker-weight-unit', next); } catch {} unitListeners.forEach(listener => listener()); }
export function useWeightUnit() { return useSyncExternalStore(listener => { unitListeners.add(listener); return () => unitListeners.delete(listener); }, () => weightUnit); }
export function formatWeight(value: number) { const converted = weightUnit === 'lb' ? value * 2.2046226218 : value; return `${Math.round(converted * 10) / 10} ${weightUnit}`; }
export const english: Record<string, string> = {
  ...nutritionEnglish,
  'Mot de passe oublié ?': 'Forgot password?',
  'Retrouve ton accès.': 'Get back on track.',
  'Renseigne ton email. On t’enverra un lien pour réinitialiser ton mot de passe.': 'Enter your email. We’ll send you a link to reset your password.',
  'Envoyer le lien': 'Send reset link',
  'Retour à la connexion': 'Back to login',
  'Si un compte correspond à cette adresse, tu recevras un lien pour choisir un nouveau mot de passe. Pense à vérifier tes spams.': 'If an account matches this address, you’ll receive a link to choose a new password. Check your spam folder too.',
  'Vérifie ta boîte mail pour confirmer ton inscription, puis connecte-toi. Pense à vérifier tes spams.': 'Check your inbox to confirm your signup, then log in. Check your spam folder too.',
  'Envoi impossible pour le moment. Réessaie plus tard.': 'Unable to send right now. Try again later.',
  'Utilise au moins 8 caractères.': 'Use at least 8 characters.',
  'Modification impossible. Réessaie ou demande un nouveau lien.': 'Unable to update. Try again or request a new link.',
  'Les mots de passe ne correspondent pas.': 'The passwords don’t match.',
  'Accès retrouvé.': 'You’re back.',
  'Un nouveau départ.': 'A fresh start.',
  'Ton mot de passe a été mis à jour. Tu peux te reconnecter.': 'Your password has been updated. You can log in again.',
  'Choisis un nouveau mot de passe pour ton compte MyGymTracker.': 'Choose a new password for your MyGymTracker account.',
  'Vérification du lien…': 'Checking your link…',
  'Mot de passe modifié.': 'Password updated.',
  'Ce lien est invalide ou expiré. Retourne à la connexion pour demander un nouveau lien.': 'This link is invalid or expired. Go back to login to request a new one.',
  'Nouveau mot de passe': 'New password',
  'Confirmer le mot de passe': 'Confirm password',
  'Enregistrer le mot de passe': 'Save password',
  'Brouillon sauvegardé sur cet appareil.': 'Draft saved on this device.',
  'Hors ligne : tu peux continuer à saisir.': 'Offline: you can keep editing.',
  'Sauvegarde locale indisponible. Garde cette page ouverte jusqu’à l’enregistrement.': 'Local saving is unavailable. Keep this page open until you save.',
  'Enregistrement impossible. Tes saisies sont conservées ici. Vérifie ta connexion puis réessaie.': 'Unable to save. Your entries are still here. Check your connection and try again.',
  'Au moins 8 caractères': 'At least 8 characters',
  'Brouillons de séances': 'Workout drafts',
  'Tes saisies sont conservées sur cet appareil. Reprends-les pour les enregistrer dans ton compte.': 'Your entries are kept on this device. Resume them to save to your account.',
  'Reprendre': 'Resume',
  'Supprimer ce brouillon ? La séance déjà enregistrée ne sera pas supprimée.': 'Delete this draft? Your saved workout will not be deleted.',
  "Bloc actuel": "Current block", "Définir comme bloc actuel": "Set as current block", "Ce bloc s’ouvrira par défaut.": "This block will open by default.",
  "Récapitulatif du bloc": "Block overview", "Charges prévues": "Planned weights", "Charge prévue": "Planned weight", "Aperçu des charges": "Weight preview", "Poids réalisé": "Actual weight", "Poids du corps": "Body weight", "minimum": "minimum", "semaine": "week",
  "Pour les dips, tractions et muscle-ups, le calcul porte sur le poids du corps + le lest. Les charges prévues correspondent uniquement au lest ajouté.": "For dips, pull-ups and muscle-ups, calculations use body weight plus added weight. Planned weights show the added weight only.",
  "Ton cycle. Tes exercices. Tes performances.": "Your cycle. Your exercises. Your performance.",
  "Préparer mon bloc": "Build my block",
  "Choisis la durée, le RPE de chaque semaine et tes exercices. Chaque semaine comprend du ×5 et du ×3.": "Choose the duration, each week's RPE and your exercises. Each week includes ×5 and ×3 work.",
  "Nombre de semaines": "Number of weeks", "Exercices du bloc": "Block exercises",
  "Tractions": "Pull-ups", "Soulevé de terre": "Deadlift", "Muscle-up": "Muscle-up",
  "Choisis au moins un exercice valide.": "Choose at least one valid exercise.",
  "Choisis de 1 à 24 semaines et un RPE valide pour chaque semaine.": "Choose 1 to 24 weeks and a valid RPE for each week.",
  "Poids du corps invalide.": "Invalid body weight.", "Paramètres de calcul invalides.": "Invalid calculation parameters.",
  "Utilisé pour calculer le lest des dips, tractions et muscle-ups.": "Used to calculate added weight for dips, pull-ups and muscle-ups.",
  "Pour les dips, tractions et muscle-ups, le calcul porte sur le poids du corps + le lest. Les charges affichées correspondent uniquement au lest ajouté (minimum 0 kg).": "For dips, pull-ups and muscle-ups, the calculation uses body weight plus added weight. The displayed weights are added weight only (minimum 0 kg).",
  "Si deux semaines consécutives donnent la même charge en ×3 ou en ×5, l’arrondi est ajusté d’un pas (+ ou −). Les charges restent modifiables.": "If consecutive weeks produce the same ×3 or ×5 weight, rounding is adjusted by one increment (+ or −). You can still edit the weights.",
  "Aperçu des charges (kg)": "Weight preview (kg)",
  "Le poids du corps est commun aux dips, tractions et muscle-ups. Les charges prévues sont recalculées ; les performances enregistrées restent intactes.": "Body weight is shared by dips, pull-ups and muscle-ups. Planned weights are recalculated; logged performances are kept.",
  "Chargement de tes entraînements…":"Loading your training…",
  "Aller au contenu":"Skip to content", "TON ESPACE":"YOUR SPACE", "La régularité fait la différence.":"Consistency makes the difference.", "Une séance à la fois.":"One workout at a time.", "Mon compte":"My account", "Ton espace personnel":"Your personal space",
  "CONSTRUIS TA PROGRESSION":"BUILD YOUR PROGRESS", "Chaque séance.":"Every workout.", "Un pas de plus.":"One step further.", "Tes entraînements, tes objectifs, ton évolution. Tout commence ici.":"Your workouts, your goals, your progress. It all starts here.", "TON ESPACE PERSONNEL":"YOUR PERSONAL SPACE", "Commence ton parcours.":"Start your journey.", "Prêt pour la suite ?":"Ready for what's next?", "Crée ton compte et prépare ta première séance.":"Create your account and plan your first workout.", "Connecte-toi pour retrouver tes entraînements.":"Log in to pick up your training.",
  "TON JOURNAL D’ENTRAÎNEMENT":"YOUR TRAINING JOURNAL", "Chaque séance compte.":"Make every workout count.", "Retrouve tes séances. Prépare la prochaine. Continue de progresser.":"Revisit your workouts. Plan the next one. Keep progressing.", "Vue d’ensemble":"Overview", "Séances enregistrées":"Saved workouts", "depuis le début":"all time", "Séries planifiées":"Planned sets", "dans tes séances":"across your workouts", "Jours d’entraînement":"Training days", "dates distinctes":"unique dates", "Rechercher une séance":"Search workouts", "Aucune séance ne correspond à ta recherche.":"No workouts match your search.",
  "À TON RYTHME":"AT YOUR PACE", "Compose ta séance, exercice après exercice.":"Build your workout, one exercise at a time.", "Charger un modèle":"Load a template", "Pars d’une base Push, Pull ou Legs et adapte-la à tes objectifs.":"Start with Push, Pull or Legs and make it your own.", "Ta séance commence ici.":"Your workout starts here.", "Ajoute ton premier exercice pour préparer tes séries.":"Add your first exercise to plan your sets.", "Supprimer l’exercice":"Delete exercise", "Supprimer la série":"Delete set", "DANS LES DÉTAILS":"A CLOSER LOOK", "UNE BASE POUR PROGRESSER":"A FOUNDATION FOR PROGRESS", "Apparence":"Appearance", "Clair":"Light", "Sombre":"Dark",
  "Bloc force":"Strength block", "Exercice":"Exercise",
  "Poids du corps (kg)":"Body weight (kg)", "Utilisé pour calculer le lest des dips et des tractions.":"Used to calculate added weight for dips and pull-ups.", "Recalculer les charges":"Recalculate weights", "Les charges prévues de cet exercice sont recalculées ; les performances enregistrées restent intactes.":"Planned weights for this exercise are recalculated; logged performances are kept.", "Le poids du corps est commun aux dips et aux tractions. Les charges prévues sont recalculées ; les performances enregistrées restent intactes.":"Body weight is shared by dips and pull-ups. Planned weights are recalculated; logged performances are kept.", "Pour les dips et tractions, le pourcentage RPE s’applique au poids du corps et au lest réunis. Le lest prévu est arrondi au pas de charge, avec un minimum de 0 kg. Ce calcul reste une estimation.":"For dips and pull-ups, the RPE percentage applies to body weight plus added weight. The prescribed added weight is rounded to the loading increment, with a minimum of 0 kg. This remains an estimate.",
  "Ce bloc utilise encore l’ancien calcul. Renseigne ton poids du corps puis recalcule les charges.":"This block still uses the previous calculation. Enter your body weight, then recalculate the weights.",
  "Réglages":"Settings", "Langue":"Language", "Langue de l’application":"App language", "La langue est mémorisée sur cet appareil.":"Your language is saved on this device.", "Unité de poids":"Weight unit", "Choisis l’unité utilisée pour afficher les charges.":"Choose the unit used to display weights.", "Kilogrammes (kg)":"Kilograms (kg)", "Livres (lb)":"Pounds (lb)",
  "Déconnexion":"Log out", "Suivi d'entraînement intelligent":"Smart workout tracking", "Séances":"Workouts", "Force":"Strength", "Chargement des blocs…":"Loading blocks…",
  "Impossible de charger tes séances et blocs. Recharge la page pour réessayer.":"Unable to load your workouts and blocks. Reload the page to try again.",
  "Des modifications du bloc ne sont pas enregistrées. Quitter quand même ?":"Your block has unsaved changes. Leave anyway?",
  "Veuillez entrer un email":"Please enter an email", "Veuillez entrer un mot de passe":"Please enter a password", "Erreur lors de l'authentification":"Authentication failed", "Erreur inconnue":"Unknown error", "Mot de passe":"Password", "Au moins 6 caractères":"At least 6 characters", "Chargement...":"Loading...", "Créer compte":"Create account", "Se connecter":"Log in", "Vous avez déjà un compte ? Connectez-vous":"Already have an account? Log in", "Pas de compte ? Créez-en un":"No account? Sign up", "☁️ Vos données sont stockées de manière sécurisée sur Supabase":"☁️ Your data is stored securely on Supabase", "votre@email.com":"you@email.com",
  "Annuler la saisie":"Cancel entry", "+ Enregistrer une série":"+ Log a set", "Poids réalisé (kg)":"Actual weight (kg)", "Reps réalisées":"Actual reps", "RPE ressenti":"Actual RPE", "Ex. : dur, propre, marge…":"E.g. hard, clean, reps in reserve…", "Ajouter au bloc":"Add to block", "Bloc enregistré dans ton compte.":"Block saved to your account.", "Enregistrement impossible. Réessaie.":"Unable to save. Try again.", "Un objectif. Quatre semaines. Tes performances.":"One goal. Four weeks. Your performance.", "+ Nouveau bloc":"+ New block", "Préparer mon bloc de 4 semaines":"Prepare my 4-week block", "RPE 7 → 8 → 8,5 → 9. Chaque semaine propose un travail en 5 reps et en 3 reps pour chaque exercice.":"RPE 7 → 8 → 8.5 → 9. Each week includes 5-rep and 3-rep work for every exercise.", "Nom du bloc":"Block name", "1RM visé ·":"Target 1RM ·", "lest ajouté":"added weight", "charge totale":"total weight", "Arrondi au plus proche :":"Rounded to nearest:", "Sem. 1 · 5 reps :":"Week 1 · 5 reps:", "Calcul : 1RM visé × pourcentage du tableau, puis arrondi. Pour les dips et tractions, le calcul porte uniquement sur le lest ; le poids de corps n’est pas inclus. Les charges restent ajustables.":"Calculation: target 1RM × table percentage, then rounded. For dips and pull-ups, only added weight is used; body weight is excluded. You can adjust the weights.", "Enregistrement…":"Saving…", "Générer et enregistrer le bloc":"Generate and save block", "Annuler":"Cancel", "Mes blocs":"My blocks", "objectifs renseignés":"targets logged", "Exercices de force":"Strength exercises", "1RM visé":"Target 1RM", "Lest ajouté":"Added weight", "Charge totale":"Total weight", "· pas de":"· increment", "Semaine du bloc":"Block week", "Sem.":"Week", "Semaine":"Week", "% du 1RM":"% of 1RM", "Charge prévue (kg)":"Planned weight (kg)", "Rétablir le calcul RPE":"Reset to RPE calculation", "Retirer cette performance du bloc ?":"Remove this performance from the block?", "Retirer":"Remove", "Modifications à enregistrer":"Unsaved changes", "Bloc enregistré":"Block saved", "La date des performances est ajoutée automatiquement.":"Performance dates are added automatically.", "Enregistrer le bloc":"Save block", "Enregistre le bloc avant de quitter cette page ou de changer de bloc.":"Save the block before leaving this page or switching blocks.", "Tableau RPE · % du 1RM":"RPE table · % of 1RM", "Référence fournie pour les calculs. Les colonnes correspondent au nombre de répétitions.":"Reference used for calculations. Columns represent the number of repetitions.", "Pourcentage du 1RM selon le RPE et les répétitions":"Percentage of 1RM by RPE and repetitions",
  "Sélectionner une séance":"Choose a workout", "groupes musculaires":"muscle groups", "← Retour aux séances":"← Back to workouts", "Groupe":"Group", "Utiliser cette séance":"Use this workout", "Êtes-vous sûr de vouloir supprimer cette séance ?":"Are you sure you want to delete this workout?", "← Retour":"← Back", "Exercices":"Exercises", "Séries":"Sets", "séries":"sets", "Série":"Set", "✏️ Modifier":"✏️ Edit", "🗑️ Supprimer":"🗑️ Delete", "Nouvelle séance":"New workout", "Séance":"Workout", "Fermer":"Close", "Modifier la séance":"Edit workout", "Enregistrer":"Save", "Nom de la séance":"Workout name", "Ex: Pull 1, Push, Legs...":"E.g. Pull 1, Push, Legs...", "📋 Charger un template de séance":"📋 Load a workout template", "+ Ajouter un exercice":"+ Add exercise", "Nom de l'exercice":"Exercise name", "Changer l'ordre de l'exercice":"Reorder exercise", "Monter l'exercice":"Move exercise up", "Monter":"Move up", "Descendre l'exercice":"Move exercise down", "Descendre":"Move down", "Poids (kg)":"Weight (kg)", "Reps (ex: 6-8)":"Reps (e.g. 6-8)", "Ex: 10 ou 6-8":"E.g. 10 or 6-8", "+ Ajouter une série":"+ Add set", "Mes Séances":"My workouts", "➕ Nouvelle Séance":"➕ New workout", "Aucune séance enregistrée":"No workouts saved", "Commencez par créer votre première séance !":"Start by creating your first workout!", "Masquer les séries":"Hide sets", "Afficher les séries":"Show sets", "exercices":"exercises", "Exercices :":"Exercises:", "Voir détails":"View details", "Modifier":"Edit", "Supprimer cette séance ?":"Delete this workout?", "Supprimer":"Delete",
  "TON POINT DE DÉPART":"YOUR STARTING POINT", "Modifier mon objectif":"Edit my goal", "Construisons ton objectif":"Set your goal", "Quelques informations pour estimer tes besoins quotidiens.":"A few details to estimate your daily needs.", "Quel est ton objectif ?":"What is your goal?", "Perdre du poids":"Lose weight", "Prendre du poids":"Gain weight", "Maintenir mon poids":"Maintain my weight", "Poids actuel (kg)":"Current weight (kg)", "Poids visé (kg)":"Target weight (kg)", "Âge (années)":"Age (years)", "Taille (cm)":"Height (cm)", "Équation de calcul":"Calculation formula", "Formule homme":"Male equation", "Formule femme":"Female equation", "Entraînements par semaine":"Workouts per week", "0–1 séance":"0–1 workouts", "2–3 séances":"2–3 workouts", "4–5 séances":"4–5 workouts", "6 séances ou plus":"6 or more workouts", "Maintien estimé":"Estimated maintenance", "Objectif proposé":"Suggested target", "jour":"day", "Ajuster manuellement l’objectif calorique":"Adjust calorie target manually", "Calories par jour (facultatif)":"Calories per day (optional)", "Estimation pour adultes : équation de Mifflin–St Jeor et facteur d’activité approximatif. Adapte-la selon ton évolution et tes besoins ; ce n’est pas un avis médical.":"Estimate for adults using the Mifflin–St Jeor equation and an approximate activity factor. Adjust it based on your progress and needs; this is not medical advice.", "Source du calcul":"Calculation source", "Saisis un objectif calorique valide.":"Enter a valid calorie target.", "Vérifie les informations saisies.":"Check the information entered.", "Enregistrer mon objectif":"Save my goal", "Renseigne des valeurs valides pour un adulte.":"Enter valid values for an adult.", "Le poids visé doit correspondre à ton objectif.":"Target weight must match your goal.", "Fréquence d’entraînement invalide.":"Invalid workout frequency.",
  "Petit-déjeuner":"Breakfast", "Déjeuner":"Lunch", "En-cas":"Snack", "Dîner":"Dinner", "Modifier un aliment":"Edit food", "Ajouter un aliment":"Add food", "Code-barres du produit":"Product barcode", "Recherche…":"Searching…", "Rechercher":"Search", "Arrêter la caméra":"Stop camera", "Scanner avec la caméra":"Scan with camera", "Tu peux aussi saisir un aliment et ses valeurs nutritionnelles manuellement.":"You can also enter a food and its nutrition values manually.", "Nom de l’aliment":"Food name", "Ex. yaourt nature":"E.g. plain yogurt", "Marque (facultatif)":"Brand (optional)", "Quantité consommée":"Amount consumed", "Unité":"Unit", "Valeurs pour 100 g ou 100 ml":"Values per 100 g or 100 ml", "Calories (kcal)":"Calories (kcal)", "Protéines (g)":"Protein (g)", "Glucides (g)":"Carbs (g)", "Lipides (g)":"Fat (g)", "Données issues d’":"Data from ", "Vérifie toujours l’étiquette du produit.":"Always check the product label.", "Vérifie le nom, la quantité et les valeurs nutritionnelles.":"Check the name, quantity and nutrition values.", "Ajouter au journal":"Add to diary", "Aperçu de la caméra":"Camera preview", "Place le code-barres dans le cadre":"Place the barcode in the frame", "Ce QR code ne contient pas de code alimentaire reconnu.":"This QR code does not contain a recognized food barcode.", "Caméra indisponible. Autorise son accès ou saisis le code-barres.":"Camera unavailable. Allow access or enter the barcode.", "Entre un code-barres de 8 à 14 chiffres.":"Enter an 8- to 14-digit barcode.", "Aliment introuvable. Tu peux l’ajouter manuellement.":"Food not found. You can add it manually.", "Recherche indisponible.":"Search unavailable.",
  "Chargement de ton journal nutrition…":"Loading your nutrition diary…", "Chargement impossible.":"Unable to load.", "Chargement de la journée…":"Loading the day…", "Enregistrement impossible.":"Unable to save.", "Suppression impossible.":"Unable to remove.", "Retirer cet aliment du journal ?":"Remove this food from the diary?", "Mange avec intention.":"Eat with intention.", "Ton objectif, tes repas, ta progression.":"Your goal, meals and progress.", "TON JOURNAL":"YOUR DIARY", "Ton assiette, ton rythme.":"Your plate, your pace.", "Suis tes repas et avance vers ton objectif, un jour à la fois.":"Track your meals and move toward your goal, one day at a time.", "Mon objectif":"My goal", "Jour précédent":"Previous day", "Jour suivant":"Next day", "Choisir une date":"Choose a date", "Aujourd’hui":"Today", "Journal du jour":"Day diary", "consommées":"consumed", "OBJECTIF DU JOUR":"DAILY TARGET", "restantes":"remaining", "au-dessus de l’objectif":"over target", "Objectif estimé à partir de ton profil. Tu peux l’ajuster dans « Mon objectif ».":"Estimated from your profile. You can adjust it in My goal.", "Protéines":"Protein", "Glucides":"Carbs", "Lipides":"Fat", "aliment":"food", "aliments":"foods", "Aucun aliment ajouté pour ce repas.":"No food added to this meal.", "Les valeurs des produits proviennent d’":"Product values come from ", "Vérifie l’étiquette et ajuste les quantités si besoin.":"Check the label and adjust quantities if needed."
  ,"Choisir une formule":"Choose a formula", "Choisis une formule de calcul.":"Choose a calculation formula.", "Poids actuel":"Current weight", "Poids visé":"Target weight", "Estimation trop basse pour proposer une perte de poids automatiquement. Demande un avis professionnel.":"Estimate too low for an automatic weight-loss target. Ask a health professional.",
  "Place le QR ou le code-barres dans le cadre":"Place the QR code or barcode in the frame", "QR lu, mais aucun code produit reconnu. Essaie le code-barres EAN sur l’emballage.":"QR code read, but no product code was found. Try the EAN barcode on the package.", "Allumer la lampe":"Turn on flashlight", "Éteindre la lampe":"Turn off flashlight", "Lampe indisponible sur cet appareil.":"Flashlight unavailable on this device.",
  "Tous droits réservés.":"All rights reserved.",
  "Nombre de séries": "Number of sets",
  "Séries en ×3": "Sets of 3 reps",
  "Séries en ×5": "Sets of 5 reps",
  "Réduction par série au-delà de 3 (%)": "Reduction per set beyond 3 (%)",
  "Réglable de 0 à 5 % selon ton ressenti.": "Adjust from 0 to 5% based on how it feels.",
  "Choisis de 1 à 10 séries et une réduction de 0 à 5 %.": "Choose 1 to 10 sets and a reduction from 0 to 5%.",
  "Base : 3 séries. Chaque série supplémentaire réduit la charge calculée de 1 % avant arrondi (5 séries : −2 %). Le RPE reste une cible estimée ; ajuste selon ton ressenti. Avec 1 ou 2 séries, la charge reste identique. La réduction est réglable par exercice après création.": "Baseline: 3 sets. Each extra set reduces the calculated load by 1% before rounding (5 sets: −2%). RPE remains an estimated target; adjust based on how it feels. With 1 or 2 sets, the load stays the same. You can adjust the reduction per exercise after creation.",
  "Charge recalculée automatiquement. Base : 3 séries ; réduction par série supplémentaire :": "Load recalculated automatically. Baseline: 3 sets; reduction per extra set:",
  "Estimation à ajuster selon le RPE ressenti.": "Adjust this estimate based on your actual RPE.",
  "séries enregistrées": "sets logged",
  "Sans réduction de charge, les arrondis suivent le calcul d’origine, quel que soit le nombre de séries. Avec une réduction active, des semaines peuvent garder la même charge pour préserver cette réduction. Les charges restent modifiables.": "Without a load reduction, rounding follows the original calculation regardless of set count. With an active reduction, weeks may keep the same load to preserve that reduction. You can still edit the weights."
};
