import { useSyncExternalStore } from 'react';
export type Language = 'fr' | 'en';
const listeners = new Set<() => void>();
let language: Language = 'fr';
try { if (localStorage.getItem('mygymtracker-language') === 'en') language = 'en'; } catch { /* Storage may be disabled. */ }
export function setLanguage(next: Language) {
  language = next;
  document.documentElement.lang = next;
  try { localStorage.setItem('mygymtracker-language', next); } catch { /* Keep the in-memory preference. */ }
  listeners.forEach(listener => listener());
}
document.documentElement.lang = language;
export function useLanguage() {
  return useSyncExternalStore(listener => { listeners.add(listener); return () => { listeners.delete(listener); }; }, () => language);
}
export function t(text: string): string { return language === 'en' ? (english[text] ?? text) : text; }
export function locale() { return language === 'en' ? 'en-GB' : 'fr-FR'; }
export const english: Record<string, string> = {
  "Chargement de tes entraînements…":"Loading your training…",
  "Aller au contenu":"Skip to content", "TON ESPACE":"YOUR SPACE", "La régularité fait la différence.":"Consistency makes the difference.", "Une séance à la fois.":"One workout at a time.", "Mon compte":"My account", "Ton espace personnel":"Your personal space",
  "CONSTRUIS TA PROGRESSION":"BUILD YOUR PROGRESS", "Chaque séance.":"Every workout.", "Un pas de plus.":"One step further.", "Tes entraînements, tes objectifs, ton évolution. Tout commence ici.":"Your workouts, your goals, your progress. It all starts here.", "TON ESPACE PERSONNEL":"YOUR PERSONAL SPACE", "Commence ton parcours.":"Start your journey.", "Prêt pour la suite ?":"Ready for what's next?", "Crée ton compte et prépare ta première séance.":"Create your account and plan your first workout.", "Connecte-toi pour retrouver tes entraînements.":"Log in to pick up your training.",
  "TON JOURNAL D’ENTRAÎNEMENT":"YOUR TRAINING JOURNAL", "Chaque séance compte.":"Make every workout count.", "Retrouve tes séances. Prépare la prochaine. Continue de progresser.":"Revisit your workouts. Plan the next one. Keep progressing.", "Vue d’ensemble":"Overview", "Séances enregistrées":"Saved workouts", "depuis le début":"all time", "Séries planifiées":"Planned sets", "dans tes séances":"across your workouts", "Jours d’entraînement":"Training days", "dates distinctes":"unique dates", "Rechercher une séance":"Search workouts", "Aucune séance ne correspond à ta recherche.":"No workouts match your search.",
  "À TON RYTHME":"AT YOUR PACE", "Compose ta séance, exercice après exercice.":"Build your workout, one exercise at a time.", "Charger un modèle":"Load a template", "Pars d’une base Push, Pull ou Legs et adapte-la à tes objectifs.":"Start with Push, Pull or Legs and make it your own.", "Ta séance commence ici.":"Your workout starts here.", "Ajoute ton premier exercice pour préparer tes séries.":"Add your first exercise to plan your sets.", "Supprimer l’exercice":"Delete exercise", "Supprimer la série":"Delete set", "DANS LES DÉTAILS":"A CLOSER LOOK", "UNE BASE POUR PROGRESSER":"A FOUNDATION FOR PROGRESS", "Apparence":"Appearance", "Clair":"Light", "Sombre":"Dark",
  "Bloc force":"Strength block", "Exercice":"Exercise",
  "Réglages":"Settings", "Langue":"Language", "Langue de l’application":"App language", "La langue est mémorisée sur cet appareil.":"Your language is saved on this device.",
  "Déconnexion":"Log out", "Suivi d'entraînement intelligent":"Smart workout tracking", "Séances":"Workouts", "Force":"Strength", "Chargement des blocs…":"Loading blocks…",
  "Impossible de charger tes séances et blocs. Recharge la page pour réessayer.":"Unable to load your workouts and blocks. Reload the page to try again.",
  "Des modifications du bloc ne sont pas enregistrées. Quitter quand même ?":"Your block has unsaved changes. Leave anyway?",
  "Veuillez entrer un email":"Please enter an email", "Veuillez entrer un mot de passe":"Please enter a password", "Erreur lors de l'authentification":"Authentication failed", "Erreur inconnue":"Unknown error", "Mot de passe":"Password", "Au moins 6 caractères":"At least 6 characters", "Chargement...":"Loading...", "Créer compte":"Create account", "Se connecter":"Log in", "Vous avez déjà un compte ? Connectez-vous":"Already have an account? Log in", "Pas de compte ? Créez-en un":"No account? Sign up", "☁️ Vos données sont stockées de manière sécurisée sur Supabase":"☁️ Your data is stored securely on Supabase", "votre@email.com":"you@email.com",
  "Annuler la saisie":"Cancel entry", "+ Enregistrer une série":"+ Log a set", "Poids réalisé (kg)":"Actual weight (kg)", "Reps réalisées":"Actual reps", "RPE ressenti":"Actual RPE", "Ex. : dur, propre, marge…":"E.g. hard, clean, reps in reserve…", "Ajouter au bloc":"Add to block", "Bloc enregistré dans ton compte.":"Block saved to your account.", "Enregistrement impossible. Réessaie.":"Unable to save. Try again.", "Un objectif. Quatre semaines. Tes performances.":"One goal. Four weeks. Your performance.", "+ Nouveau bloc":"+ New block", "Préparer mon bloc de 4 semaines":"Prepare my 4-week block", "RPE 7 → 8 → 8,5 → 9. Chaque semaine propose un travail en 5 reps et en 3 reps pour chaque exercice.":"RPE 7 → 8 → 8.5 → 9. Each week includes 5-rep and 3-rep work for every exercise.", "Nom du bloc":"Block name", "1RM visé ·":"Target 1RM ·", "lest ajouté":"added weight", "charge totale":"total weight", "Arrondi au plus proche :":"Rounded to nearest:", "Sem. 1 · 5 reps :":"Week 1 · 5 reps:", "Calcul : 1RM visé × pourcentage du tableau, puis arrondi. Pour les dips et tractions, le calcul porte uniquement sur le lest ; le poids de corps n’est pas inclus. Les charges restent ajustables.":"Calculation: target 1RM × table percentage, then rounded. For dips and pull-ups, only added weight is used; body weight is excluded. You can adjust the weights.", "Enregistrement…":"Saving…", "Générer et enregistrer le bloc":"Generate and save block", "Annuler":"Cancel", "Mes blocs":"My blocks", "objectifs renseignés":"targets logged", "Exercices de force":"Strength exercises", "1RM visé":"Target 1RM", "Lest ajouté":"Added weight", "Charge totale":"Total weight", "· pas de":"· increment", "Semaine du bloc":"Block week", "Sem.":"Week", "Semaine":"Week", "% du 1RM":"% of 1RM", "Charge prévue (kg)":"Planned weight (kg)", "Rétablir le calcul RPE":"Reset to RPE calculation", "Retirer cette performance du bloc ?":"Remove this performance from the block?", "Retirer":"Remove", "Modifications à enregistrer":"Unsaved changes", "Bloc enregistré":"Block saved", "La date des performances est ajoutée automatiquement.":"Performance dates are added automatically.", "Enregistrer le bloc":"Save block", "Enregistre le bloc avant de quitter cette page ou de changer de bloc.":"Save the block before leaving this page or switching blocks.", "Tableau RPE · % du 1RM":"RPE table · % of 1RM", "Référence fournie pour les calculs. Les colonnes correspondent au nombre de répétitions.":"Reference used for calculations. Columns represent the number of repetitions.", "Pourcentage du 1RM selon le RPE et les répétitions":"Percentage of 1RM by RPE and repetitions",
  "Sélectionner une séance":"Choose a workout", "groupes musculaires":"muscle groups", "← Retour aux séances":"← Back to workouts", "Groupe":"Group", "Utiliser cette séance":"Use this workout", "Êtes-vous sûr de vouloir supprimer cette séance ?":"Are you sure you want to delete this workout?", "← Retour":"← Back", "Exercices":"Exercises", "Séries":"Sets", "séries":"sets", "Série":"Set", "✏️ Modifier":"✏️ Edit", "🗑️ Supprimer":"🗑️ Delete", "Nouvelle séance":"New workout", "Séance":"Workout", "Fermer":"Close", "Modifier la séance":"Edit workout", "Enregistrer":"Save", "Nom de la séance":"Workout name", "Ex: Pull 1, Push, Legs...":"E.g. Pull 1, Push, Legs...", "📋 Charger un template de séance":"📋 Load a workout template", "+ Ajouter un exercice":"+ Add exercise", "Nom de l'exercice":"Exercise name", "Changer l'ordre de l'exercice":"Reorder exercise", "Monter l'exercice":"Move exercise up", "Monter":"Move up", "Descendre l'exercice":"Move exercise down", "Descendre":"Move down", "Poids (kg)":"Weight (kg)", "Reps (ex: 6-8)":"Reps (e.g. 6-8)", "Ex: 10 ou 6-8":"E.g. 10 or 6-8", "+ Ajouter une série":"+ Add set", "Mes Séances":"My workouts", "➕ Nouvelle Séance":"➕ New workout", "Aucune séance enregistrée":"No workouts saved", "Commencez par créer votre première séance !":"Start by creating your first workout!", "Masquer les séries":"Hide sets", "Afficher les séries":"Show sets", "exercices":"exercises", "Exercices :":"Exercises:", "Voir détails":"View details", "Modifier":"Edit", "Supprimer cette séance ?":"Delete this workout?", "Supprimer":"Delete"
};
