export const nutritionEnglish:Record<string,string>={
  'Chargement de la caméra…':'Loading camera…',
  'Tout':'All',
  'Nom de l’aliment ou marque…':'Food name or brand…',
  'Recherche automatique par nom ou marque à partir de 3 caractères.':'Automatic name or brand search from 3 characters.',
  'Recherche des produits de marque…':'Searching branded products…',
  'Saisis au moins 3 caractères ou appuie sur Chercher.':'Enter at least 3 characters or press Find.',
  'Recherche indisponible pour le moment.':'Search temporarily unavailable.',
  'La base des produits de marque ne répond pas. Réessaie ou utilise les aliments courants.':'The branded food database is unavailable. Retry or use common foods.',
  'Nom ou marque : appuie sur Chercher pour trouver les produits emballés.':'Name or brand: press Find to search packaged products.',
  'Aliment générique · sans marque':'Generic food · no brand',
  'Marque non renseignée':'Brand not provided',
  'Valeurs nutritionnelles à compléter':'Nutrition facts to complete',
  'Boisson':'Drink',
  'Fruit frais':'Fresh fruit',
  'Produit liquide':'Liquid product',
  'Aucun produit emballé trouvé pour ce nom ou cette marque.':'No packaged products found for this name or brand.',
  'Autorise la caméra dans ton navigateur. Les images restent sur ton appareil.':'Allow camera access in your browser. Images stay on your device.',
  'En attente de l’autorisation caméra…':'Waiting for camera permission…',
  'Accès caméra refusé. Autorise la caméra pour ce site dans ton navigateur, puis réessaie.':'Camera access denied. Allow the camera for this site in your browser, then retry.',
  'Aucune caméra détectée sur cet appareil. Tu peux saisir le code-barres ci-dessous.':'No camera detected on this device. You can enter the barcode below.',
  'La caméra est occupée ou indisponible. Ferme les autres applications qui l’utilisent, puis réessaie.':'The camera is busy or unavailable. Close other apps using it, then retry.',
  'Caméra indisponible. Réessaie ou saisis le code-barres ci-dessous.':'Camera unavailable. Retry or enter the barcode below.',
  'La caméra nécessite HTTPS ou localhost. Ouvre l’application depuis une adresse sécurisée.':'The camera requires HTTPS or localhost. Open the app from a secure address.',
  'Ce navigateur ne permet pas l’accès à la caméra. Essaie Safari ou Chrome.':'This browser does not support camera access. Try Safari or Chrome.',
  'Bien manger. À ton rythme.':'Eat well. At your own pace.',
  'Une vue claire de tes repas, de ton énergie et de ton activité.':'A clear view of your meals, energy and activity.',
  'Bilan de la journée':'Daily overview',
  'kcal restantes':'kcal remaining','kcal au-dessus':'kcal over',
  'TON ÉQUILIBRE DU JOUR':'YOUR DAILY BALANCE',
  'Chaque repas compte.':'Every meal counts.',
  'Une journée, pas un verdict.':'One day, not a verdict.',
  'mangées':'eaten','objectif kcal':'kcal goal','activité kcal':'activity kcal',
  'Objectif de base':'Base goal','kcal de marche estimées':'estimated walking kcal',
  'Fibres':'Fiber','protéines':'protein','fibres':'fiber','Repère':'Reference','partiel':'partial',
  'de l’objectif kcal':'of the calorie goal',
  'Total de fibres partiel : valeurs absentes pour':'Partial fiber total: values missing for',
  'aliment.':'food.','aliments.':'foods.',
  'Mes repas':'My meals','aliments aujourd’hui':'foods today',
  'Qu’as-tu mangé ?':'What did you eat?','Rechercher un aliment':'Search for food',
  'Mon activité':'My activity','Au fil du jour':'Throughout the day','Mes pas':'My steps',
  'Santé · importés':'Health · imported','Non connecté':'Not connected',
  'Seuls les pas au-delà de ton activité habituelle ajustent l’objectif.':'Only steps above your usual activity adjust the goal.',
  'L’ajustement calorique est désactivé. Tu peux l’activer dans Mon objectif.':'Calorie adjustment is off. You can enable it in My goal.',
  'Dernière mise à jour':'Last updated','Connecter Santé':'Connect Health','Actualiser':'Refresh',
  'Corriger les pas':'Correct steps','Hydratation':'Hydration','aujourd’hui':'today',
  'Note tes verres d’eau, sans pression. Tes besoins varient selon ta journée.':'Log your water without pressure. Your needs vary with your day.',
  'La régularité, pas la perfection.':'Consistency, not perfection.',
  'Les portions et calories sont des repères. Écoute aussi ta faim et ton énergie.':'Portions and calories are guides. Listen to your hunger and energy too.',
  'Données alimentaires':'Food data','Calculs indicatifs, pas un avis médical.':'Indicative calculations, not medical advice.',
  'Corriger mes pas':'Correct my steps',
  'Correction ponctuelle du total du jour. Un prochain envoi Santé peut le remplacer.':'One-off correction to the daily total. A later Health delivery may replace it.',
  'Saisis un nombre entier de pas entre 0 et 100 000.':'Enter a whole number of steps between 0 and 100,000.',
  'Total de pas':'Step total','Mode d’ajout':'Logging method','Code-barres':'Barcode','Créer un aliment':'Create food',
  'Banane, riz, poulet, marque…':'Banana, rice, chicken, brand…','Effacer la recherche':'Clear search','Chercher':'Find',
  'Aliments courants':'Common foods','Produits de marque':'Branded foods','Récents':'Recent',
  'Résultats':'Results','Pour commencer':'Get started','Ton journal':'Your diary','Aliment courant':'Common food',
  'Cherche ton produit par son nom.':'Search for your product by name.',
  'Tes aliments récents apparaîtront ici.':'Your recent foods will appear here.',
  'Aucun résultat pour ce nom.':'No results for this name.',
  'Appuie sur Chercher pour interroger Open Food Facts.':'Press Find to search Open Food Facts.',
  'Essaie un autre nom ou ajoute-le manuellement.':'Try another name or create a food.',
  'Scanne l’emballage pour retrouver ses valeurs nutritionnelles.':'Scan the packaging to find its nutrition facts.',
  'Ou saisis le code-barres':'Or enter the barcode',
  'Nouvel aliment':'New food','Aliment personnel':'Custom food','Retour à la recherche':'Back to search',
  'Quelle quantité ?':'How much?','Pour cette portion':'For this portion',
  'La portion de l’étiquette est proposée ; adapte-la à ce que tu as mangé.':'The label serving is suggested; adjust it to what you ate.',
  'Portions indicatives, pas une prescription. Ajuste selon ce que tu as mangé.':'Indicative portions, not a prescription. Adjust to what you ate.',
  'portion':'serving','Portion de départ':'Starting portion','Portion de l’étiquette':'Label serving',
  '1 banane moyenne':'1 medium banana','1 pomme moyenne':'1 medium apple','1 œuf':'1 egg','1 pot':'1 pot','1 cuillère à soupe':'1 tablespoon','1 bol':'1 bowl','1 tranche':'1 slice',
  'Nom et valeurs nutritionnelles':'Name and nutrition facts','Valeurs pour 100 g':'Values per 100 g','Valeurs pour 100 ml':'Values per 100 ml','Fibres (g)':'Fiber (g)','Inconnues':'Unknown',
  'Certaines valeurs manquent. Complète-les avec l’étiquette avant l’ajout.':'Some values are missing. Complete them from the label before adding.',
  'Fibres non renseignées : elles ne seront pas comptées comme zéro connu.':'Fiber is missing: it will not be treated as a known zero.',
  'Valeurs moyennes et données déclarées : vérifie le produit et son état cru ou cuit.':'Average and reported values: check the food and whether it is raw or cooked.',
  'Enregistrement impossible. Tes saisies sont conservées ici. Vérifie ta connexion puis réessaie.':'Unable to save. Your input is kept here. Check your connection and retry.',
  'Catalogue alimentaire indisponible.':'Food catalog unavailable.','Saisis de 2 à 80 caractères.':'Enter 2 to 80 characters.',
  'Trop de recherches. Patiente une minute.':'Too many searches. Wait a minute.',
  'Fibres, pas et ajustement calorique':'Fiber, steps and calorie adjustment',
  'Repère de fibres (g / jour)':'Fiber reference (g / day)','Repère de pas / jour':'Step reference / day',
  'Pas habituels déjà inclus':'Usual steps already included',
  'Ajuster les calories avec les pas supplémentaires':'Adjust calories with additional steps',
  'Le calcul de base inclut déjà ton activité. Pour limiter le double comptage, seuls les pas au-delà de ton seuil habituel ajoutent une estimation de marche nette, plafonnée à 600 kcal. Ajustement désactivé par défaut.':'The base calculation already includes activity. To limit double-counting, only steps above your usual threshold add estimated net walking energy, capped at 600 kcal. Adjustment is off by default.',
  'Repères de fibres':'Fiber references','Repères personnalisables, non prescrits.':'Customizable references, not prescriptions.',
  'Vérifie tes repères de fibres et de pas.':'Check your fiber and step references.',
  'Un enregistrement est déjà en cours.':'A save is already in progress.',
  'Attends le chargement de la journée avant de modifier le journal.':'Wait for the day to load before editing your diary.',
  'La journée a changé. Réessaie.':'The day has changed. Retry.',
  'Santé, sans saisie quotidienne.':'Health, without daily input.','CONNEXION IPHONE':'IPHONE CONNECTION',
  'Une automatisation iOS envoie uniquement la date et le total de pas. Le site ne lit pas directement Santé et ne demande pas ton mot de passe.':'An iOS automation sends only the date and step total. The website does not read Health directly or ask for your password.',
  'Clé autorisée jusqu’au':'Key valid until','Configurer le Raccourci reste nécessaire.':'You still need to set up the Shortcut.',
  'Autoriser l’envoi des pas':'Authorize step delivery',
  'La clé est privée, révocable et limitée à tes pas. Elle ne permet ni de lire ton compte ni de modifier tes repas.':'The key is private, revocable and limited to steps. It cannot read your account or change meals.',
  'Créer une nouvelle clé':'Create a new key','Créer ma clé de connexion':'Create my connection key',
  'Copie-la maintenant dans Raccourcis. Elle ne sera plus affichée après fermeture. Ne la partage pas.':'Copy it to Shortcuts now. It will not be shown again after closing. Do not share it.',
  'Copier l’en-tête Authorization':'Copy Authorization header','Copié':'Copied','Clé privée de synchronisation':'Private sync key',
  'Créer le Raccourci « MyGymTracker Pas »':'Create the “MyGymTracker Pas” Shortcut',
  'Dans Raccourcis, ajoute « Rechercher des échantillons de Santé » : type Pas, aujourd’hui, sans limite. Filtre sur une seule source (ton iPhone OU ta montre), pour ne pas additionner leurs doublons.':'In Shortcuts, add Find Health Samples: Steps, today, no limit. Filter to one source (iPhone OR watch) to avoid adding duplicate samples.',
  'Récupère la Valeur des échantillons, puis calcule leur Somme. Formate la date actuelle en yyyy-MM-dd.':'Get the Value of the samples and calculate their Sum. Format the current date as yyyy-MM-dd.',
  'Ajoute « Obtenir le contenu de l’URL » avec ces paramètres :':'Add Get Contents of URL with these settings:',
  'TA_CLÉ_PRIVÉE':'YOUR_PRIVATE_KEY',
  'Choisis un corps JSON : date = Date formatée (Texte), steps = Somme (Nombre). Lance-le une première fois et autorise l’accès à Santé et au site. Vérifie que le nombre de pas est cohérent avec Santé.':'Choose a JSON body: date = Formatted Date (Text), steps = Sum (Number). Run it once and allow access to Health and the website. Check the total against Health.',
  'Programmer l’envoi automatique':'Schedule automatic delivery',
  'Raccourcis → Automatisation → Heure de la journée → Tous les jours → Exécuter immédiatement → MyGymTracker Pas. Par exemple à 21 h ; ajoute d’autres horaires si tu veux plus de mises à jour.':'Shortcuts → Automation → Time of Day → Daily → Run Immediately → MyGymTracker Pas. For example at 9 pm; add other times for more updates.',
  'iOS peut bloquer la lecture de Santé lorsque l’iPhone est verrouillé. Une connexion réseau et l’accès aux données Santé sont nécessaires : teste l’automatisation sur ton téléphone. Ce n’est pas une synchronisation temps réel garantie.':'iOS may block Health access while the iPhone is locked. A network connection and Health access are required: test the automation on your phone. This is not guaranteed real-time sync.',
  'Révoquer la connexion':'Revoke connection','Guide Apple des automatisations':'Apple automation guide',
  'Seuls les pas sont transmis. Aucun export complet de Santé.':'Only steps are sent. No complete Health export.',
  'Remplacer la clé ? L’ancien Raccourci devra être mis à jour.':'Replace the key? The old Shortcut will need updating.',
  'Déconnecter Santé ? Le Raccourci ne pourra plus envoyer de pas.':'Disconnect Health? The Shortcut will no longer be able to send steps.',
  'Activation impossible.':'Unable to enable sync.','Copie indisponible. Sélectionne la clé.':'Copy unavailable. Select the key.',
};
