export const statisticsEnglish: Record<string,string> = {
  'Statistiques':'Statistics', 'STATISTIQUES / TA PROGRESSION':'STATISTICS / YOUR PROGRESS',
  'Tes efforts prennent forme.':'See your progress take shape.',
  'Tes charges, ton poids, ta régularité. Un regard sur le chemin parcouru.':'Your lifts, body weight and consistency. See how far you have come.',
  'Actualiser les statistiques':'Refresh statistics', 'Exporter en Excel':'Export to Excel', 'Préparation…':'Preparing…',
  '4 semaines':'4 weeks', '12 semaines':'12 weeks', '6 mois':'6 months', 'Période des statistiques':'Statistics period',
  'Jours d’entraînement':'Training days', 'jours':'days', 'Séances et force, sans doublons':'Workouts and strength, without duplicates',
  'Séries de force':'Strength sets', 'réalisées':'logged', 'Les charges prévues ne comptent pas':'Planned loads do not count',
  'Semaines actives':'Active weeks', 'Au moins un jour d’entraînement':'At least one training day',
  'Dernier poids connu':'Latest known weight', 'Depuis ton journal Nutrition':'From your Nutrition diary',
  'PROGRESSION EN FORCE':'STRENGTH PROGRESS', 'Des charges qui évoluent.':'Your lifts over time.', 'Réalisé':'Logged',
  'Exercice de force':'Strength exercise', 'Répétitions comparées':'Repetition filter', 'Aucun exercice':'No exercise',
  'répétitions':'repetitions', 'Toutes les répétitions':'All repetitions', 'Dernière charge':'Latest load',
  'Évolution sur la période':'Change over the period', 'Meilleure charge':'Best load', 'Évolution des charges réalisées':'Logged load history',
  'Aucune performance sur cette sélection':'No performances for this selection',
  'Enregistre tes séries dans Force ou essaie une autre période et un autre nombre de répétitions.':'Log sets in Strength or try another period or repetition filter.',
  'Lest ajouté uniquement, hors poids du corps':'Added weight only, excluding body weight', 'Charge réalisée':'Logged load',
  'Meilleure série de chaque jour':'Best set of each day',
  'Les répétitions varient : une charge plus lourde ne signifie pas toujours une meilleure performance.':'Repetitions vary: a heavier load does not always mean a better performance.',
  'Voir les valeurs du graphique':'View chart values', 'Date':'Date', 'Charge':'Load', 'Répétitions':'Repetitions',
  'POIDS DU CORPS':'BODY WEIGHT', 'Ton évolution, simplement.':'Your weight over time.',
  'Enregistre tes premières pesées':'Log your first measurements', 'sur la période':'over the period', 'Évolution du poids du corps':'Body weight history',
  'Ton historique commence ici':'Your history starts here',
  'Ajoute une pesée dans Nutrition. Les anciennes valeurs du profil n’ont pas de date : elles ne sont pas inventées sur le graphique.':'Log a measurement in Nutrition. Old profile weights have no date and are not backdated on the chart.',
  'Configure ton objectif dans Nutrition':'Set your goal in Nutrition', 'Ajouter une pesée':'Log body weight',
  'Une première mesure. La courbe apparaîtra dès la deuxième pesée.':'Your first measurement. The line will appear after your second measurement.',
  'Voir les pesées':'View measurements', 'Poids':'Weight', 'RÉGULARITÉ':'CONSISTENCY',
  'Une semaine à la fois.':'One week at a time.', 'actives':'active',
  'Jours d’entraînement par semaine. Une journée compte une seule fois, même avec plusieurs exercices.':'Training days per week. A day counts once, even with several exercises.',
  'Jours d’entraînement par semaine':'Training days per week', 'Semaine du':'Week of', 'jours d’entraînement':'training days',
  'Les semaines aux extrémités peuvent être partielles.':'Boundary weeks may be partial.',
  'REPÈRES DE FORCE':'STRENGTH MILESTONES', 'Tes meilleurs lifts.':'Your best lifts.', 'Ouvrir Force':'Open Strength',
  'Meilleure charge réalisée sur la période, avec le nombre de répétitions associé.':'Best logged load in the period, with the associated repetitions.',
  'Pas encore de performance':'No performance yet', 'de lest':'added', 'Tes records viendront ici':'Your records will appear here',
  'Crée ton premier bloc et enregistre tes séries dans Force.':'Create your first block and log your sets in Strength.',
  'Volume de force réalisé : charge × répétitions, hors poids du corps.':'Logged strength volume: load × repetitions, excluding body weight.',
  'Volume réalisé':'Logged volume',
  'L’export contient toute la période et tous les exercices, indépendamment du filtre du graphique.':'The export includes the full period and all exercises, regardless of the chart filter.',
  'Impossible de charger tes statistiques. Réessaie.':'Unable to load your statistics. Try again.', 'Chargement des statistiques…':'Loading statistics…',
  'Export Excel prêt. Vérifie tes téléchargements.':'Excel export ready. Check your downloads.', 'Export impossible. Réessaie.':'Export failed. Try again.',
  'Ma pesée':'Body weight', 'Poids du jour':'Weight for this day', 'Modifier la pesée':'Edit measurement',
  'Une pesée datée pour suivre ton évolution dans Statistiques. Ton objectif calorique reste inchangé.':'A dated measurement to track your progress in Statistics. Your calorie goal stays unchanged.'
};
